#!/bin/bash

# A script to interactively provide metadata for a comment on all Ogg Vorbis files in a directory, generally used for songs downloaded from YouTube because they don't have metadata. This is in place of doing it manually in Rhythmbox or another music player.

#Exit on errors
set -e

#If there are no ogg files, exit the script
for file in *.ogg; do
	if [ "${file}" = "*.ogg" ]; then # When there are no files matching a wildcard, the output is the wildcard, so check for that to know there are no files
		echo "No files found. Please execute in a directory with .ogg files." && exit 1
	fi
done

#Set tracktotal here so loop() has it regardless of function called prior
tracktotal=$(ls *.ogg | wc -l)

# For now this will still ask for some information but in the future will probably call another script to interface with the Discogs API
default_variables() {
	echo "Track total: $tracktotal"

	disctotal=1
	echo "Disc total: $disctotal"
	
	# Get artist from one directory back
	ask_artist=false
	artist=$(echo "$PWD" | awk -F/ '{print $(NF-1)}')
	echo "Artist: $artist"

	# Get album from current directory
	ask_album=false
	album=$(echo "$PWD" | awk -F/ '{print $NF}')
	echo "Album: $album"

	ask_year=false	
	read -p "Year: " year

	ask_genre=false
	read -p "Genre: " genre

	ask_tracknum=true
	
	ask_title=false
}

#Find global values for all files by asking user
get_globals() {
	read -p "Is there one disc? (Y/n) " single_disc
	case $single_disc in
		n|N) read -p "How many discs in total? " disctotal;;
		*) disctotal=1;;
	esac

	read -p "Is there one artist? (Y/n) " single_artist
	case $single_artist in
		n|N) ask_artist=true;;
		*) ask_artist=false;;
	esac
	
	read -p "Is there one album? (Y/n) " single_album
	case $single_album in
		n|N) ask_album=true;;
		*) ask_album=false;;
	esac
	
	read -p "Is there one year? (Y/n) " single_year
	case $single_year in
		n|N) ask_year=true;;
		*) ask_year=false;;
	esac

	read -p "Is there one genre? (Y/n) " single_genre
	case $single_genre in
		n|N) ask_genre=true;;
		*) ask_genre=false;;
	esac

	read -p "Are files sequential by track number? (y/N) " sequential
	case $sequential in
		y|Y) ask_tracknum=false;;
		*) ask_tracknum=true;;
	esac

	read -p "Should Title be file name? (Y/n) " title_as_file
	case $title_as_file in
		n|N) ask_title=true;;
		*) ask_title=false;;
	esac

	if [ $ask_year = false ]; then
		read -p "Year: " year
	fi

	if [ $ask_artist = false ]; then
		read -p "Artist: " artist
	fi

	if [ $ask_album = false ]; then
		read -p "Album: " album
	fi

	if [ $ask_genre = false ]; then
		read -p "Genre: " genre
	fi
}

#Ask user for values that change between files
get_comments() {
	if [ $ask_title = true ]; then
		read -p "Title: " title
	fi

	if [ $ask_year = true ]; then
		read -p "Year: " year
	fi

	if [ $ask_tracknum = true ]; then
		read -p "Track Number: " tracknumber
	fi
	
	if [ $disctotal -ne 1 ]; then
		read -p "Disc Number: " discnumber
	else
		discnumber=1
	fi

	if [ $ask_artist = true ]; then
		read -p "Artist: " artist
	fi
	
	if [ $ask_album = true ]; then
		read -p "Album: " album
	fi

	if [ $ask_genre = true ]; then
		read -p "Genre: " genre
	fi
}

loop () {
	# Set a default track number in case files are sequential
	tracknumber=1
	for file in *.ogg; do
		echo "File: $file"
		
		#Get user-inputted values
		get_comments

		#If we don't ask user for title, make it file name (exclude file extensions)
		if [ $ask_title = false ]; then
			if [[ "$file" == *".ogg" ]]; then
				title=$(echo "$file" | sed 's/\.[^.]*$//')
			else
				title="$file"
			fi
		fi
		
		#Make the comment
		vorbiscomment -w "$file" \
			-t "TITLE=$title" \
			-t "DATE=$year" \
			-t "TRACKNUMBER=$tracknumber" \
			-t "TRACKTOTAL=$tracktotal" \
			-t "DISCNUMBER=$discnumber" \
			-t "DISCTOTAL=$disctotal" \
			-t "ARTIST=$artist" \
			-t "ALBUM=$album" \
			-t "GENRE=$genre"

		#Only increment track number if files are sequential
		if [ $ask_tracknum = false ]; then
			tracknumber=$((tracknumber+1))
		fi
	done
}

# Get global variables (or defaults), do the for loop then exit

#fix this
#if [ -n $2 ]; then
#	echo "Please only pass one option to this script. Valid options are -d (or leave blank). -h, or -i." && exit 1
#fi

case $1 in
	-i|--interactive) get_globals;;
	-h|--help) echo "Use in a directory with .ogg files. If you want to manually enter values (for example, if your file structure differs from the one this script looks for), use -i or --interactive." && exit 0;;
	""|-d|--defaults) default_variables;;
	*) echo "Option $1 is not recognized. Valid options are -d (or leave blank). -h, or -i." && exit 1;;
esac

loop && exit 0
